---

- name: Install host dependencies
  pacman:
    name:
      - python-docker
      - python-dnspython
    state: present
    update_cache: true

- name: Ensure Docker is installed
  pacman:
    name:
      - docker
    state: present
  when: matrix_docker_installation_enabled | bool
