---

- name: Get rid of old files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ matrix_base_data_path }}/environment-variables"
    - "{{ matrix_base_data_path }}/scratchpad"
